// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestamoLisbrosAPI.Models;

namespace PrestamoLisbrosAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191104022808_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nacionalidad");

                    b.Property<string>("Nombre");

                    b.HasKey("IdAutor");

                    b.ToTable("Autor");

                    b.HasData(
                        new
                        {
                            IdAutor = 1,
                            Nacionalidad = "USA",
                            Nombre = "Mario Benedetti"
                        },
                        new
                        {
                            IdAutor = 2,
                            Nacionalidad = "Francia",
                            Nombre = "Justino Aragon"
                        },
                        new
                        {
                            IdAutor = 3,
                            Nacionalidad = "USA",
                            Nombre = "Jefferson Jhonson"
                        });
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("IdLector")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CI");

                    b.Property<string>("Carrera");

                    b.Property<string>("Dierccion");

                    b.Property<int>("Edad");

                    b.Property<string>("Nombre");

                    b.HasKey("IdLector");

                    b.ToTable("Estudiante");

                    b.HasData(
                        new
                        {
                            IdLector = 1,
                            CI = "294568",
                            Carrera = "Informática",
                            Dierccion = "Calle Masaya Residencial Mayales Casa B-22",
                            Edad = 19,
                            Nombre = "Felipe Loayza Beramendi"
                        },
                        new
                        {
                            IdLector = 2,
                            CI = "294568",
                            Carrera = "Informática",
                            Dierccion = "Calle Masaya Residencial Mayales Casa B-22",
                            Edad = 20,
                            Nombre = "Daniel Gonzales"
                        },
                        new
                        {
                            IdLector = 3,
                            CI = "897867",
                            Carrera = "Quimica",
                            Dierccion = "Calle Granada Residencial Mayales Casa B-92",
                            Edad = 18,
                            Nombre = "Josefina Gomez"
                        });
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.LibAut", b =>
                {
                    b.Property<int>("IdAutor");

                    b.Property<int>("IdLibro");

                    b.HasKey("IdAutor", "IdLibro");

                    b.HasIndex("IdLibro");

                    b.ToTable("LibAut");

                    b.HasData(
                        new
                        {
                            IdAutor = 1,
                            IdLibro = 1
                        },
                        new
                        {
                            IdAutor = 1,
                            IdLibro = 2
                        },
                        new
                        {
                            IdAutor = 2,
                            IdLibro = 3
                        });
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<string>("Editorial");

                    b.Property<string>("Titulo");

                    b.HasKey("IdLibro");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            IdLibro = 1,
                            Area = "Internet",
                            Editorial = "Alfa",
                            Titulo = "Visual Studio Net"
                        },
                        new
                        {
                            IdLibro = 2,
                            Area = "Base de Datos",
                            Editorial = "Omega",
                            Titulo = "Base de Datos"
                        },
                        new
                        {
                            IdLibro = 3,
                            Area = "Internet",
                            Editorial = "Alfa",
                            Titulo = "Hacking"
                        });
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.Prestamo", b =>
                {
                    b.Property<int>("IdLector");

                    b.Property<int>("IdLibro");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("Date");

                    b.Property<bool>("Devuelto");

                    b.Property<DateTime>("FechaDevolucion");

                    b.HasKey("IdLector", "IdLibro", "FechaPrestamo");

                    b.HasIndex("IdLibro");

                    b.ToTable("Prestamo");

                    b.HasData(
                        new
                        {
                            IdLector = 1,
                            IdLibro = 1,
                            FechaPrestamo = new DateTime(2007, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Devuelto = false,
                            FechaDevolucion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdLector = 1,
                            IdLibro = 1,
                            FechaPrestamo = new DateTime(2007, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Devuelto = false,
                            FechaDevolucion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdLector = 2,
                            IdLibro = 2,
                            FechaPrestamo = new DateTime(2007, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Devuelto = false,
                            FechaDevolucion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdLector = 3,
                            IdLibro = 2,
                            FechaPrestamo = new DateTime(2007, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Devuelto = false,
                            FechaDevolucion = new DateTime(2007, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.LibAut", b =>
                {
                    b.HasOne("PrestamoLisbrosAPI.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoLisbrosAPI.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrestamoLisbrosAPI.Models.Prestamo", b =>
                {
                    b.HasOne("PrestamoLisbrosAPI.Models.Estudiante", "Lector")
                        .WithMany()
                        .HasForeignKey("IdLector")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrestamoLisbrosAPI.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
